### PR TITLE
Add `behindProxy` option to `App.listen()`

### PR DESCRIPTION
**Pull request by dahlia**
Addresses <https://github.com/denoland/fresh/issues/2660>.

The `behindProxy` option lets Fresh respect `X-Forwarded-Proto`, `X-Forwarded-Host`, `X-Forwarded-Port`, and `X-Forwarded-For` headers (if any).  This is useful when Fresh is behind a reverse proxy like nginx or Caddy.

### CODE REVIEW

**Review by marvinhagemeister — COMMENTED** [review]
Thanks for making a PR. I feel like this is much better implemented as a middleware instead of a configuration option as it's not something everyone needs. With Fresh 2 the aim is to keep the config as minimal as possible.

**Comment by dahlia** [comment]
@marvinhagemeister Does Fresh's middleware support replacing request objects? At first glance, it doesn't seem to support that.

**Comment by marvinhagemeister** [comment]
Yes, to replace the `Request` object do this:

```ts
function proxyMiddleware(ctx) {
  const req =  new Request()
  
  // Replace current request
  ctx.req = req;
  ctx.url = new URL(req.url)
  
  return ctx.next()
}
```

**Comment by dahlia** [comment]
Apparently [`FreshContext.req` is readonly](https://github.com/denoland/fresh/blob/e0f65319cd48753f5b9b4784f996a0eaf7e6ebff/src/context.ts#L36).

**Comment by dahlia** [comment]
@marvinhagemeister Apparently [`FreshContext.req` is readonly](https://github.com/denoland/fresh/blob/e0f65319cd48753f5b9b4784f996a0eaf7e6ebff/src/context.ts#L36).  Should I suppress the TypeScript error and set `ctx.req` by force?

**Comment by marvinhagemeister** [comment]
Let's remove the `readonly` in `FreshContext`.

**Comment by dahlia** [comment]
> Let's remove the `readonly` in `FreshContext`.

@marvinhagemeister: Just opened a [separate pull request](https://github.com/denoland/fresh/pull/2751).

**Pull request closed without merging**
