### PR TITLE
fix: KV tests not skipped without --unstable

### PR DESCRIPTION
**Pull request by marvinhagemeister**

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
@iuioiua Is there any way to close the KV instance without dispatching `beforeunload`?  #1808 broke the ability to run tests without `--unstable`.

**Comment by iuioiua** [comment]
Tests without `--unstable` on my local machine on the latest stable version of Deno.
```
deno 1.37.0 (release, aarch64-apple-darwin)
v8 11.8.172.3
typescript 5.2.2
```
The thing is, the KV OAuth module closes the KV instance on the `beforeunload` event (see [here](https://github.com/denoland/deno_kv_oauth/blob/e6ed8eb8dd472428cae4278769ef1f42ef29b643/lib/_core.ts#L43-L45)). So we may be hitting a bug in canary. I've submitted #1820, which should be merged before this PR to confirm this bug.

**Comment by iuioiua** [comment]
Yeah, IDK why this is happening... I'd disable sanitizers and add a `@todo` for now haha

**Comment by iuioiua** [comment]
Closing as `--unstable` is no longer used in tests.

**Pull request closed without merging**
