### PR TITLE
feat: prevent duplicate routes when generating manifest

### LINKED ISSUE #1378: fresh@1.2.0 Fetch "POST" request not working, JSON data not sending to server api.
Fresh POST request denied to take JSON data. hence , Fresh server api not able to receive body's json data.

Fresh 'version@1.2.0'.
Screenshot from 2023-06-30 19-37-11

File : 'routes/users/github.ts'.

`
 import { Handlers } from "$fresh/server.ts";
 import { User } from "../../types/user.ts";
export const handler: Handlers = {
  async POST(req) {
    console.log(req)
    const body = await req.json();
    const res = await fetch(`https://api.github.com/users/${body.q}`);
    if (res.status === 404) {
      return new Response(null, { status: 404 });
    }
    const user: User = await res.json();
    return new Response(JSON.stringify(user));
  },
 };
`

File : 'routes/users/github.tsx'.

`
import Layout from '../../components/Layout.tsx';
  import SearchGithubUser from "../../islands/SearchGithubUser.tsx";
 import { tw } from "twind";
export default function Github() {
    return (
        <Layout>
            <div class={tw`flex justify-center`}>
                <div class={tw`m-auto`}>
                    <SearchGithubUser />
                </div>
            </div>
        </Layout>
    )
}
`

File : 'islands/SearchGihubUser.tsx'.
`
import { useState } from "preact/hooks";
import { tw } from "twind";
import { User } from "../types/user.ts";

export default function SearchGithubUser() {
    const [user, setUser] = useState<User>();
    const [q, setQ] = useState<string>('');

    async function onSubmit(e: Event) {
        e.preventDefault();
        const res = await fetch('/users/github', {
            method: "POST",
            body: JSON.stringify({ q })
        });
        const data: User = await res.json();
        if (res.ok) {
            setUser(data)
        }
    }

    function handleInput(e: { target: { value: string | ((prevState: string) => string); }; }) {
        setQ(e.target.value)
    }

    return (
        <div>
            <section>
                <form onSubmit={onSubmit}>
                    <input
                        type="text"
                        class={tw`border rounded shadow-md px-4 py-2 w-72`}
                        name="q"
                        value={q}
                        onChange={() => handleInput}
                        placeholder="Search Github user by Username"
                    />
                    <button class={tw`border rounded shadow-md px-4 py-2 bg-blue-800 text-white ml-4`} type="submit">Search</button>
                </form>
            </section>

            {user?.name && (
                <section class={tw`mt-10`}>
                    <a href={user.html_url} target="_blank">
                        <p class={tw`text-2xl text-center`}>Username: {user.login}</p>
                        
                    </a>

                </section>
            )}
        </div>
    );
}
`

File : 'deno.json'.
Screenshot from 2023-06-30 19-38-22

Fresh 'version@1.0.1'.
Screenshot from 2023-06-30 19-39-47

File : 'routes/users/github.ts'.

`
import { Handlers}  from "$fresh/server.ts"

export const handler: Handlers = {
    async POST(req) {
        const body = await req.json();
        
        const res = await fetch(`https://api.github.com/users/${body.q}`);
        if(res.status === 404){
          return new Response(null,{status:404});
        }
    
        const user = await res.json();
        return new Response(JSON.stringify(user));
      }
}`

File : 'routes/users/github.tsx'.
`
/** @jsx h */
import {h} from "preact"
import Layout from '../../components/layouts.tsx';
import SearchGithubUser from "../../islands/SearchGithubUser.tsx";
import {tw} from "@twind";

export default function Github() {

  return (
    <Layout>
      <div class={tw`flex justify-center`}>
        <div class={tw`m-auto`}>
          <SearchGithubUser />
        </div>
      </div>
    </Layout>
  )
}
`
File : 'islands/SearchGithubUser.tsx'.

`
/** @jsx h */
import {h} from "preact"
import { useState } from "preact/hooks";
import {tw} from "@twind";

export default function SearchGithubUser() {
  const [user, setUser] = useState();
  const [q, setQ] = useState('');

  async function onSubmit(e) {
    e.preventDefault();
    const res = await fetch('/users/github', {
      method:"POST",
      body: JSON.stringify({q})
    });
    const data = await res.json();
    if(res.ok){
      setUser(data)
    }
  }

  function handleInput(e) {
    setQ(e.target.value)
  }

  return (
    <div>
      <section>
        <form onSubmit={onSubmit}>
          <input
            type="text"
            class={tw`border rounded shadow-md px-4 py-2 w-72`}
            name="q"
            value={q}
            onChange={handleInput}
            placeholder="Search Github user by Username"
          />
          <button class={tw`border rounded shadow-md px-4 py-2 bg-blue-800 text-white ml-4`} type="submit">Search</button>
        </form>
      </section>

      {user?.name && (
        <section class={tw`mt-10`}>
          <a href={user.html_url} target="_blank">
            <p class={tw`text-2xl text-center`}>Username: {user.login}</p>
            
          </a>
        </section>
      )}
    </div>
  );
}
`
File : 'import_map.json'.

`
{
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.0.1/",
    "preact": "https://esm.sh/preact@10.8.2",
    "preact/": "https://esm.sh/preact@10.8.2/",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.0?deps=preact@10.8.2",
    "@twind": "./utils/twind.ts",
    "twind": "https://esm.sh/twind@0.16.17",
    "twind/": "https://esm.sh/twind@0.16.17/"
  }
}
`

### PR DESCRIPTION
**Pull request by deer**
closes https://github.com/denoland/fresh/issues/1378

Now if someone has e.g. `routes/user.ts` and `routes/user.tsx` we'll throw an error message when generating the manifest, instead of allowing people to shoot themselves in the foot and have massive confusion / pain.

I need some help with the test. It definitely asserts the functionality, but if the startup process doesn't error, the test hangs. Is there an easy way to tell `Deno.Command` to stop after X seconds?

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
The test becomes a little easier when you create a `./tests/fixture_my_test` folder instead of creating a project from scratch with every run.

What do you mean the startup process doesn't error? Does it print the correct exit code or is that wrong too? Wondering if it's either not being teared down correctly or if the error message isn't flushed before the process aborts.

**Comment by deer** [comment]
Ok, I can refactor it to introduce a new test folder. I have another PR planned after this in the same space, so maybe it's good to have a new fixture.

What I mean is the following. When I do:
```ts
const cliProcess = new Deno.Command(Deno.execPath(), {
  args: [
    "run",
    "-A",
    `tests/fixture_route_analysis/dev.ts`,
  ],
  stdin: "null",
  stdout: "piped",
  stderr: "piped",
});
```
and the project doesn't error (because I reverted my fix, in order to test that the test fails correctly), then the test just runs forever. Because the server successfully starts up.

**Comment by marvinhagemeister** [comment]
Right, I see the issue. The server is a long running process so `Deno.Command` never finishes if it booted successfully. Instead you could spawn the process similar to how it's done in `startFreshServer()` and check if the server is ready message was printed. That means the server booted successfully and the duplicate route error logic wasn't hit as that part runs before that.

**Comment by deer** [comment]
Thanks for the hint. I've updated the test and when I revert my fix, it actually fails. Reapplying the fix causes the test to pass.

**Comment by deer** [comment]
In theory this is ready to review, but we've hit the flaky test on windows (noting the OS for record keeping).

**Review by marvinhagemeister — APPROVED** [review]

**Comment by marvinhagemeister** [comment]
LGTM, Re-ran the CI for now. Not sure why it was flaky

**Pull request merged**
