### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by kazuma0129**
Corrected document path.

### CODE REVIEW

**Review by un-versed — CHANGES_REQUESTED** [review]
You need to rename the markdown file `docs/concepts/architechture.md` to `docs/concepts/architecture.md`

As I did here

[3d83b894803dc145d07e85d8c1944cd7c5f5738d](https://github.com/un-versed/fresh/commit/3d83b894803dc145d07e85d8c1944cd7c5f5738d)

See https://github.com/denoland/fresh/issues/454

**Comment by nikableh** [comment]
> You need to rename the markdown file `docs/concepts/architechture.md` to `docs/concepts/architecture.md`
> 
> As I did here
> 
> [3d83b894803dc145d07e85d8c1944cd7c5f5738d](https://github.com/un-versed/fresh/commit/3d83b894803dc145d07e85d8c1944cd7c5f5738d)
> 
> See #454

Btw, you can just paste full commit hash like this`3d83b894803dc145d07e85d8c1944cd7c5f5738d` and GitHub will automatically turn it into a link: 3d83b894803dc145d07e85d8c1944cd7c5f5738d

**Comment by un-versed** [comment]
> > You need to rename the markdown file `docs/concepts/architechture.md` to `docs/concepts/architecture.md`
> > As I did here
> > [3d83b894803dc145d07e85d8c1944cd7c5f5738d](https://github.com/un-versed/fresh/commit/3d83b894803dc145d07e85d8c1944cd7c5f5738d)
> > See #454
> 
> Btw, you can just paste full commit hash like this`3d83b894803dc145d07e85d8c1944cd7c5f5738d` and GitHub will automatically turn it into a link: [3d83b89](https://github.com/denoland/fresh/commit/3d83b894803dc145d07e85d8c1944cd7c5f5738d)

Oh, thanks haha i didnt know (:

**Comment by kazuma0129** [comment]
> You need to rename the markdown file docs/concepts/architechture.md to docs/concepts/architecture.md
> 
> As I did here
> 
> [3d83b894803dc145d07e85d8c1944cd7c5f5738d](https://github.com/un-versed/fresh/commit/3d83b894803dc145d07e85d8c1944cd7c5f5738d)
> 
> See https://github.com/denoland/fresh/issues/454


Thank you. I fixed this. 7dcb78dcbee8e19c3743396f532cddfe9c0fe43d

**Review by un-versed — APPROVED** [review]

**Comment by lucacasonato** [comment]
Need a redirect from the old to the new. https://github.com/denoland/fresh/pull/295#issuecomment-1168992730

**Review by kt3k — APPROVED** [review]
LGTM

**Pull request merged**
