### PR TITLE
feat: support multiple middlewares with the same matcher

### PR DESCRIPTION
**Pull request by ahuigo**
This `mergeHandler()` could be used to 
1. Merge handlers.
2. Control the order of handlers manually

It is necessary in many situations. https://github.com/denoland/fresh/issues/549

### CODE REVIEW

**Comment by ZackarySantana** [comment]
@ahuigo I like the flexibility the merge handler method provides. Do you think it would be worth having each handler handle calling the next handler (similar to how express middleware does it)?

I'm thinking in the context of a handler that should stop the continuation of middleware- whether for performance or since the rest doesn't matter (like your middleware test that does a 204 response, the following middleware wouldn't do much)

**Review by lucacasonato — COMMENTED** [review]
Seems much easier if we just allow users to export an `Array<Handler>` from middleware routes. WDYT of that?

This would also allow us to avoid adding the `Proxy` complexity.

**Comment by ahuigo** [comment]
Can't agree any more.

> Seems much easier if we just allow users to export an `Array<Handler>` from middleware routes. WDYT of that?
> 
> This would also allow us to avoid adding the `Proxy` complexity.

I think there are many methods, but I don't know which one is better.

## Method 1
Completely exposes `ctx.handlers` to the users. 
```
// src/server/types.ts
export interface MiddlewareHandlerContext<State = Record<string, unknown>>
  extends ConnInfo {
  next: () => Promise<Response>;
  state: State;
  // expose
  handlers: Handler[];
}
```

The downside is that users may misuse it.
For example:
1. Misusing `ctx.handlers.push(handler)`  instead of `ctx.handlers.unshift(handler)` 
2. Misusing `ctx.handlers=[new]` instead of `ctx.handlers=[new, ...old]`


## Method 2
Exposing `ctx.prependHandler(handler)` only is  safer and easier to use(I prefer this).
```ts
export interface MiddlewareHandlerContext<State = Record<string, unknown>>
  extends ConnInfo {
  next: () => Promise<Response>;
  state: State;
 // expose
  prependHandler(handler: Handler):void;
}
```
I pushed a demo here: https://github.com/denoland/fresh/compare/main...ahuigo:fresh:feat/handler?diff=split
**Changes**
I found that `ctx: MiddlewareHandlerContext` is passed to `handler(req, ctx: HandlerContext)`,
so `HandlerContext` and `MiddlewareHandlerContext` should be same object, and I re-alias`MiddlewareHandlerContext` to `HandlerContext` in my code.

**Comment by lucacasonato** [comment]
What I mean is supporting:
```
// routes/_middleware.ts

export const handler = [
  middleware1,
  middleware2,
];
```

**Comment by jcs224** [comment]
> What I mean is supporting:
> 
> ```
> // routes/_middleware.ts
> 
> export const handler = [
>   middleware1,
>   middleware2,
> ];
> ```

This would be my preference. In fact, when I want to bundle some middleware together and use it in various places, this is how I do it in Oak. Each array entry is an Oak middleware:

```ts
export default [
  Session,
  Inertia.initMiddleware(),
  async (ctx: Context, next: () => Promise<unknown>) => {
    ctx.state.inertia.setShared({
      errors: await ctx.state.session.get('errors')
    })
    await next()
  }
] as const
```

**Comment by ahuigo** [comment]
My latest commit has implemented this logic.

> ```
> // routes/_middleware.ts
> 
> export const handler = [
>   middleware1,
>   middleware2,
> ];
> ```

Just two things I'm struggling with.

1. First, wether it is necessary to support  **`Handler[]` only**  instead of  **single `Handler`** , which makes the implementation and usage be more simpler, but  causes **break changes**.

2. Second, is it necessary to support multiple handlers for **component handler**?
For example:
```ts
// routes/index.tsx
export const handler: Handlers = {
  GET:[
      corsHandler,
      logHandler,
      (req, ctx)=> {
          ....
      }
  ],
};
```

**Comment by lucacasonato** [comment]
> First, wether it is necessary to support Handler[] only instead of single Handler , which makes the implementation and usage be more simpler, but causes break changes.

We are past 1.0, so we can not make breaking changes. Both should be supported.

> Second, is it necessary to support multiple handlers for component handler?

I don't think so. If this need comes up in the future, we can look into it then.

**Review by lucacasonato — APPROVED** [review]
Thank you!

**Comment by zenyr** [comment]
For the time being (1.0.2) I've adopted original @ahuigo 's solution in my userland code.
```ts
// lib/mergeHandlers.ts
import { MiddlewareHandlerContext } from '$fresh/server.ts';

type Handler<T> = (req: Request, ctx: MiddlewareHandlerContext<T>) => Promise<Response> | Response;

// Merge middleware handlers
export function mergeHandlers<T>(...handlers: Handler<T>[]) {
  return (_req: Request, ctx: MiddlewareHandlerContext<T>) => {
    const innerHandlers = [...handlers];
    const proxy: MiddlewareHandlerContext<T> = new Proxy(ctx, {
      get: (orgCtx, prop: keyof MiddlewareHandlerContext<T>) => {
        if (prop === 'next') {
          const handler = innerHandlers.shift();
          if (handler) {
            return async () => await handler(_req, proxy);
          }
        }
        return orgCtx[prop];
      },
    });
    return proxy.next();
  };
}



// routes/_middleware.ts
import { mergeHandlers } from '$/lib/mergeHandlers.ts';
// ...snip...
export type State = WithRedis & WithSession;
export const handler = mergeHandlers(redisMiddleware, sessionMiddleware);
```

**Pull request merged**
