### PR TITLE
fix: prevent folks messing with the fresh manifest

### PR DESCRIPTION
**Pull request by lucacasonato**
I am looking at you James.

### CODE REVIEW

**Comment by imjamesb** [comment]
Wow that was really fast...

**Review by crowlKats — APPROVED** [review]
agreed

**Comment by aapoalas** [comment]
> Wow that was really fast...

We're watching history in the making.

**Comment by imjamesb** [comment]
Oh god the name :joy: can't believe this was done in 8 minutes

**Pull request merged**
