### PR TITLE
Invoke getTime() on the Date value and not on the date signal

### PR DESCRIPTION
**Pull request by najumancheril**
Fix typo in example code

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]
Good catch! Thanks for filing a PR 🎉

**Comment by marvinhagemeister** [comment]
@najumancheril  Looks like the changes need a format to pass CI. You can do that by running `deno fmt`

**Comment by najumancheril** [comment]
I have made the following changes:
- Fixed a second location where code was using now rather than now.value
- Fixed format
- Reordered the code a bit so we compute seconds once up front. This avoids the annoying "The big event is happening in 0 seconds." message due to timer jitter. Instead, we show "...1 second" and then party. This also reduces the number of now.value references from 2 to 1. Unlike the other edits, this change is not a typo and totally optional. Let me know if you don't want it at all or if you want it in a separate pull request.

**Review by marvinhagemeister — APPROVED** [review]
Awesome, thanks for the PR 👍

**Pull request merged**
