### PR TITLE
chore: Refactor CLI tests

### PR DESCRIPTION
**Pull request by smitssjors**
As discussed in [here](https://github.com/denoland/fresh/pull/1696#issuecomment-1706347305), this PR:
- Splits up the CLI tests making them easier to find.
- Refactors the update tests to remove some of the duplication.

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]
Awesome, this is great! Thank you so much for making the tests cleaner 👍

**Comment by marvinhagemeister** [comment]
Looks like there is a remaining CI failure on windows.

**Comment by smitssjors** [comment]
@marvinhagemeister Should be fixed but I can't confirm as I am on Mac. Windows gave a different error message than Mac and Linux for files not found. I removed the argument so the error message is not checked anymore.

**Comment by iuioiua** [comment]
@smitssjors, could you please resolve the merge conflict?

**Pull request merged**
