### PR TITLE
Add: Add a string type to know that our function will return a string

### PR DESCRIPTION
**Pull request by lausuarez02**
### Description
Add a type for the function to know that it will return a string

Issue: #1369

### CODE REVIEW

**Review by marvinhagemeister — COMMENTED** [review]
Looks like the code is not formatted correctly. A quick `deno fmt` should resolve that.

**Comment by deer** [comment]
Do we actually need this? It seems like typescript can always infer that this returns a string, so I'm not sure what this does. That being said, I'm still new to typescript, so maybe I'm missing something.

If anything, it seems like we should _remove_ the static typing from the 2nd method in this file, `assetSrcSet`. It's currently declared like this:
```ts
export function assetSrcSet(srcset: string): string {
```
and returns like this:
```ts
  return constructed.join(",");
```
so we know (and so does typescript) it always returns a string.

**Comment by marvinhagemeister** [comment]
@deer It's more of a cosmetic change, since like you said TS can infer those types. It would help in cases where changes suddenly change the inferred return type though. But that said in all the years working with TS my experience is that this is more of a theoretical risk that I haven't encountered in practice. But I don't mind if somebody wants to add these return types to ramp up on the code base. So I'm happy to merge such PRs when CI passes.

**Comment by lausuarez02** [comment]
It's just like @marvinhagemeister said. It's more about a theoretical risk rather than an actual risk and also for me is to continue with the typing just like i've seen in other functions just like the next one which has a :string as a return. 
Thank you both!

**Review by marvinhagemeister — APPROVED** [review]

**Pull request merged**
