### PR TITLE
Add a global nav

### PR DESCRIPTION
**Pull request by hashrock**

### CODE REVIEW

**Comment by kt3k** [comment]
`components/Nav.ts` doesn't seem used from anywhere. Maybe you forgot to rename DocsHeader to Nav?

**Comment by kt3k** [comment]
NavigationBar component is imported from `routes/components.tsx`, `routes/index.tsx`, and `routes/showcase.tsx`, but they are not used anymore (no-unused-var lint rule is disabled in .tsx files iirc)

**Comment by hashrock** [comment]
@kt3k Thanks for your review! Renamed the jsx file and apply design update - ptal

**Review by ry — APPROVED** [review]
LGTM

**Pull request merged**
