### PR TITLE
Add 404 and 500 page #446

### PR DESCRIPTION
**Pull request by michael-pfister**
I found #446 under 'good first issue', the initial pull request was left behind.

### CODE REVIEW

**Comment by michael-pfister** [comment]
the 500 page displays the exact same component with different text

image
image

**Comment by hashrock** [comment]
I'm not sure this could be a problem, but the PR is mixed up with past commits. Can this be fixed?

スクリーンショット 2022-08-15 16 44 50

**Comment by michael-pfister** [comment]
hey @hashrock nice to see you👋

I'm not exactly sure why GitHub is showing those past commits, these are all commits that have been merged to https://github.com/denoland/fresh. My branch says it's 10 commits ahead of the master branch even though it's not, I'll try to figure this out.

We should be fine with merging this though if you look at the https://github.com/denoland/fresh/pull/614/files it won't apply any changes from my prior commits.

**Comment by michael-pfister** [comment]
I need to redo any changes and make a new PR

image

**Pull request merged**
