### PR TITLE
chore: update for deno 1.33

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR updates the code for Deno 1.33.x to solve errors on the CI. See https://github.com/denoland/fresh/actions/runs/4834957340/jobs/8616765955?pr=1138

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
Hm looks like puppeteer has trouble starting in a particular test.

**Comment by marvinhagemeister** [comment]
Investigated a little bit and it seems like `browser.close()` hangs for multiple minutes. The test itself runs fairly quick.

**Comment by lucacasonato** [comment]
@marvinhagemeister The puppeteer issue should bee fixed in 1.33.1 _I think_. @littledivy was working on it yesterday.

**Comment by lucacasonato** [comment]
Oh I see - it only hangs on the close. I wonder if the new WebSocket implementation is not sending the `"close"` event for some reason.

**Comment by lucacasonato** [comment]
It is reproducible in a minimal example: https://github.com/denoland/deno/issues/18912.

Maybe let's lock the tests to 1.32.5 until this is fixed (and disable canary).

**Comment by lucacasonato** [comment]
Since there is now a fix in canary, I have disabled 1.x tests for now. We can re-enable after 1.31.2 is released.

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks

**Pull request merged**
