### PR TITLE
Make LinkButton island

### PR DESCRIPTION
**Pull request by oliver-jenny**
Add 'island' tag to LinkButton

### CODE REVIEW

**Comment by iuioiua** [comment]
`<LinkButton />` is a component. It's in the `components` folder.

**Comment by oliver-jenny** [comment]
> `<LinkButton />` is a component. It's in the `components` folder.

Yes but like all the buttons found on the 'Component' route on the page have a little green tag next to them which sais, they are an island... Correct me if i'm wrong but this should also be marked as island right? I mean its a button which theoraticly in a project would have js code

**Comment by hashrock** [comment]
This is intended. A LinkButton is actually an anchor link that looks like a button and does not require JS.

**Comment by oliver-jenny** [comment]
> 

Well thanks for the explanation!
Guess I still have  lot to learn -> new to Fresh and happy about every advice :)

**Pull request closed without merging**
