### PR TITLE
refactor: use `useSignal()` on the starter `counter.tsx`

### PR DESCRIPTION
**Pull request by flemmingmiguel**
Having useSignal in the initial example could help adoption of it as the store for islands

### CODE REVIEW

**Comment by lucacasonato** [comment]
There is currently a bug in @preact/signals + preact-render-to-string that is resulting in a minor memory leak. I want to make sure this is fixed before we recommend that folks use signals.

**Comment by lino-levan** [comment]
Is this still a bug? I wasn't able to find an issue on either [@preact/signals](https://github.com/preactjs/signals/issues) or [preact-render-to-string](https://github.com/preactjs/preact-render-to-string/issues)?

The closest thing I see is this issue: [preact-render-to-string#191](https://github.com/preactjs/preact-render-to-string/issues/191), but the timing doesn't make sense and it's closed anyways.

**Comment by flemmingmiguel** [comment]
I think that was before the 1.1 of Preact signals, I have the latest versions working with no issues and made a small PR to bump the dependencies of the starter project [fresh#873](https://github.com/denoland/fresh/pull/873)

**Comment by iuioiua** [comment]
I'll close this PR as it's being superseded by #1234. I'm sorry we didn't get to this earlier, @flemmingmiguel. Either way, thank you very much.

**Comment by flemmingmiguel** [comment]
Hey amazing to see the repo moving , was away for the past weeks due to some health issues, happy with the news that the framework is about to speed up

**Pull request closed without merging**
