### PR TITLE
fix: add missing state property to interface

### LINKED ISSUE #1578: 404 page props are missing state
#1264 added the `state` property automatically to all pages (`PageProps`, `AppProps`, `UnknownPageProps`), since the code code was updated to automatically pass this in. But `state` was not added to the `UnknownPageProps` interface in the same PR, which seems like an oversight given that [`ctx.state` passed to and used in `renderNotFound`](https://github.com/denoland/fresh/blob/main/src/server/context.ts#L699).

It would make it a lot easier to use shared state data for missing pages if this was corrected.

### PR DESCRIPTION
**Pull request by csvn**
Corrects the props interface used in 404 pages to reflect that `state` is available as well.

Closes #1578

### CODE REVIEW

**Comment by deer** [comment]
Thanks for taking the initiative to open a PR. What about adding a test to make sure this doesn't get broken in the future?

**Comment by csvn** [comment]
@deer I could not find any references on how to test pure Typescript changes/types. There's no existing `types_test.ts` to add to. Would this mean creating a new `fixture_???` purely to check types? Should we create a `types_test.ts` that is just type checked and does something like below?

```ts
export default function NotFound(props: UnknownPageProps<{ foo: number }, { bar: boolean }>) {
  props.data.foo satisfies number;
  props.state.bar satisfies boolean;
}
```

The above would be enough to test the `UnknownPageProps` type, but not sure where to put it to be type checked.

**Comment by deer** [comment]
I meant a functional test that confirms the state is actually passed into the test _404 page. Currently there's a `tests/fixture/routes/_404.tsx` file that you could possibly modify. Look at how the tests are done in the `main_test.ts` file. Perhaps you can piggyback on an existing `_middleware.ts` which sets the state, but try going to an invalid url. That should get the state set, and then route to the 404.

**Comment by deer** [comment]
I meant a functional test that confirms the state is actually passed into the test _404 page. Currently there's a `tests/fixture/routes/_404.tsx` file that you could possibly modify. Look at how the tests are done in the `main_test.ts` file. Perhaps you can piggyback on an existing `_middleware.ts` which sets the state, but try going to an invalid url. That should get the state set, and then route to the 404.

**Comment by csvn** [comment]
I gave it a try. I added some types for the generics, and updated the `_404.tsx` file.
Not sure if I should add a new test case, or updating existing one was enough

Let me know what you think 😄

**Review by deer — APPROVED** [review]
I think this testing approach is fine.

**Review by marvinhagemeister — APPROVED** [review]
LGTM, thanks for making a PR 👍

**Comment by marvinhagemeister** [comment]
Looks like the CI is failing due to formatting issues. You can resolve these by running `deno fmt` locally and committing the changes.

**Comment by csvn** [comment]
Sorry, thought I had format on automatically on save, and workflow did not when I made the PR. Hope fully it should be OK now 😀

**Review by marvinhagemeister — APPROVED** [review]

**Pull request merged**
