### PR TITLE
[Docs] Enhanced CSR Layout

### PR DESCRIPTION
**Pull request by birkskyum**
With Fresh 1.5, the Client Side Routing should allow for a more smooth experience when browsing the Fresh docs where the scroll position of the sidebar is maintained

### CODE REVIEW

**Comment by birkskyum** [comment]
I made some general improvements to the layout, but the issue with scroll persist - also when clicking the "next-page" buttons etc. I need a way to make fresh go to the top of the nested route / partial on navigation, which arguably should be the default behaviour using naïve <a href> links. Whichever setup is used for the deno docs those also does it correctly https://docs.deno.com/runtime/manual

**Comment by marvinhagemeister** [comment]
Nice this is shaping up nicely!

Found two minor issues:

1. The header color has changed on the main site:

Screenshot 2023-10-11 at 15 17 31

2. The header behaves a bit strange when scrolling to the edge of a page. I think that's because it's positioned as `sticky`. We should probably go with `fixed` instead and give the main content area some padding

https://github.com/denoland/fresh/assets/1062408/cae9f8a4-f1c1-4553-a195-a1c086aaa238

**Comment by marvinhagemeister** [comment]
Note to self, befor merging this:

- [ ] Check home page on desktop
- [ ] Check home page on mobile
- [ ] Check docs page on desktop
- [ ] Check docs page on mobile
- [ ] Check scroll behaviour on home + docs page
- [ ] Click through a few sites to check if something has changed unintentionally

**Comment by birkskyum** [comment]
Alright, I think I've cleared these cases. I didn't pay attention to the header being used in other areas initially.

**Comment by birkskyum** [comment]
I ended up removing the stickiness of the navigation, because it's actually nicer to have have more room for the content. The existing site also doesn't have sticky top nav.

**Comment by birkskyum** [comment]
I also changed the mobile nav for more consistent design:

Screenshot 2023-10-11 at 16 22 20
Screenshot 2023-10-11 at 16 22 07

**Comment by birkskyum** [comment]
Made a few more changes, to polish the sidebar aesthetics a bit, and i think it's ready to go:
- Sidebar has full screen height
- Mobile sidebar is remove if the window is made larger while it's visible.
- Fresh logo is sticky in sidebar - nothing else is.



Screenshot 2023-10-11 at 17 12 15


Screenshot 2023-10-11 at 17 12 21

**Comment by birkskyum** [comment]
I managed to align "showcase, components" etc. with the other pages.

**Comment by birkskyum** [comment]
ready for review.

**Comment by marvinhagemeister** [comment]
This is shaping up to be really cool! I like the small border above the sidebar. That's a great idea and a nice touch 👍 

Something looks off with the sidebar in mobile mode:

Screenshot 2023-10-12 at 13 50 17


The alignment of the search box and the page content seems to have diverged a bit.

Screenshot 2023-10-12 at 13 50 39

**Comment by birkskyum** [comment]
Good catch - I've addressed these two issues.

I got the inspiration to make the sidebar like that from https://unocss.dev/integrations/cli

Screenshot 2023-10-12 at 14 08 09
Screenshot 2023-10-12 at 14 07 58

**Review by marvinhagemeister — APPROVED** [review]
Nice, this is really cool and makes the docs page feel much better. Thanks for PR'ing this 👍

**Pull request merged**
