### PR TITLE
docs: mention required `--unstable` flag in Deno KV OAuth example

### PR DESCRIPTION
**Pull request by revgum**
I ran into some friction getting this example to work and felt like a note in the documentation would really have helped.

https://github.com/denoland/deno/issues/19992#issuecomment-1660389090 lead me to the answer.

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]
Good call, thanks for adding this to the docs 👍

**Comment by marvinhagemeister** [comment]
Looks like a quick `deno fmt` should make the CI green.

**Review by iuioiua — APPROVED** [review]

**Comment by revgum** [comment]
@marvinhagemeister I wasn't making any changes to code files.. just markdown, would `deno fmt` do anything with those? I'll rebase and try this again..?

**Comment by iuioiua** [comment]
Yes, `deno fmt` also formats markdown.

**Comment by EthanThatOneKid** [comment]
Thanks for following up on this! For me, this PR meets the conditions to resolve https://github.com/denoland/deno/issues/19992#issuecomment-1660389090.

**Pull request merged**
