### PR TITLE
feat: Use href instead of origin on Partial 

### PR DESCRIPTION
**Pull request by tlgimenes**
Use `location.href` on partials so we can create refresh buttons without relying on islands or on the request

The idea is to be able to write code like this:
```tsx
const Refresh () => {
   return <button f-partial="?refresh">Refresh Page</button>
}
```

instead of this
```tsx
const Refresh ({href}: {href: string}) => {
   const url = new URL(href)
   
   url.searchParams.set('refresh', "true")
   
   return <button f-partial=`${url.href}`>Refresh Page</button>
}
```

### CODE REVIEW

**Review by marvinhagemeister — COMMENTED** [review]
Great idea! Let's add a test case for this.

**Comment by tlgimenes** [comment]
Just added some tests. Please let me know if you need anything else :)

**Review by marvinhagemeister — APPROVED** [review]
Awesome, looks great! Thanks for adding this 👍

**Comment by tlgimenes** [comment]
Just saw the tests were failing, now they are all passing :)

**Pull request merged**
