### PR TITLE
fix: change MultiHandler back to Handlers

### LINKED ISSUE #1350: Confusing naming `handler` when types is plural `Handlers
This is tripping folks up (for good reason). We currently expect the export to be named `handler` but the type name is the same word in plural: `Handlers`. See https://discord.com/channels/684898665143206084/991511118524715139/1121692086886993970

```ts
// Export is singular "handler", type is plural
export const handler: Handlers = {
  // ...
}
```

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR reverts #1360 . The deprecation of the `Handlers` type caused a bit of churn in our docs. After a bit of back and forth internally we felt that keeping it `Handlers` and throwing an error instead, when a `handlers` export detected is a better approach.

An additional benefit is that the object notation is more widely used and it makes sense to make that as ergonomic as possible.

Fixes #1350

### CODE REVIEW

**Comment by iuioiua** [comment]
What about using a `handlers` variable name instead of `handler`? That makes the most sense to me.

**Comment by marvinhagemeister** [comment]
@iuioiua that in itself would be a breaking change if we just changed that. We could allow both, but that's also weird.

**Comment by iuioiua** [comment]
True. How much would it complicate things if we supported both during a deprecation period, _if_ we were to do so? To elaborate, I'd assume that having a `handlers` variable name match its type name `Handlers` would be most apparent to a newcomer.

**Review by iuioiua — APPROVED** [review]
Revert LGTM! I think we should consider moving to a `handlers` variables name in another issue or something.

**Pull request merged**
