### PR TITLE
fix(server): middleware order incorrect

### LINKED ISSUE #1090: Middleware execution order does not follow documentation
I have the following two middleware files:
```sh
/routes/[environment]/[difficulty]/_middleware.ts
/routes/_middleware.ts
```
I put a `console.log(import.meta.url)` in the top of the handler function of each one.

When I visit the URL matching `/routes/[environment]/[difficulty]/index.ts`, the logs happen in the following order:
```sh
/routes/[environment]/[difficulty]/_middleware.ts
/routes/_middleware.ts
```

This seems contrary to the docs, which state:
>For a request to `/admin` the request flows like this:
>
>1. The `routes/_middleware.ts` middleware is invoked.
>1. Calling `ctx.next()` will invoke the `routes/admin/_middleware.ts` middleware.
>1. Calling `ctx.next()` will invoke the `routes/admin/index.ts` handler.

Is this a bug, perhaps caused by the "nested parameters" of my route (i.e. the `/[environment]/[difficulty]/`)?

### PR DESCRIPTION
**Pull request by deer**
closes https://github.com/denoland/fresh/issues/1090

As we're building up the `ServerContext`, part of the construction involves sorting the routes and middlewares like this:
```
sortRoutes(routes);
sortRoutes(middlewares);
```

Sadly it seems like the sort isn't actually doing anything. We can see this by showing the state before and after:
```
middlewares.forEach(x => console.log(x.pattern));
sortRoutes(middlewares);
middlewares.forEach(x => console.log(x.pattern));
```
then we get the following:
```
{/*}?
/layeredMdw{/*}?
/layeredMdw/layer2{/*}?
/layeredMdw/layer2/layer3{/*}?
/layeredMdw/nesting/:tenant/:environment{/*}?
/layeredMdw/nesting/:tenant{/*}?
/layeredMdw/nesting{/*}?
{/*}?
/layeredMdw{/*}?
/layeredMdw/layer2{/*}?
/layeredMdw/layer2/layer3{/*}?
/layeredMdw/nesting/:tenant/:environment{/*}?
/layeredMdw/nesting/:tenant{/*}?
/layeredMdw/nesting{/*}?
```
So we didn't change anything. With the improved sorting method for middleware (the primary change in this PR), we now get the following:
```
{/*}?
/layeredMdw{/*}?
/layeredMdw/layer2{/*}?
/layeredMdw/layer2/layer3{/*}?
/layeredMdw/nesting/:tenant/:environment{/*}?
/layeredMdw/nesting/:tenant{/*}?
/layeredMdw/nesting{/*}?
{/*}?
/layeredMdw{/*}?
/layeredMdw/layer2{/*}?
/layeredMdw/nesting{/*}?
/layeredMdw/layer2/layer3{/*}?
/layeredMdw/nesting/:tenant{/*}?
/layeredMdw/nesting/:tenant/:environment{/*}?
```

To  implement this, I split out the sorting for middleware into a new `sortMiddleware` method, because I didn't want to impact too much. I introduced a `route_sorting_test` file which asserts the new order of `middleware`, and asserts the existing order of `routes`.

Additionally, there's a functional test reproducing the case from @benadamstyles . I have some routes like this:
1. /routes/layeredMdw/nesting/_middleware.ts
2. /routes/layeredMdw/nesting/[tenant]/_middleware.ts
3. /routes/layeredMdw/nesting/[tenant]/[environment]/_middleware.ts
4. /routes/layeredMdw/nesting/[tenant]/[environment]/[id].tsx

And I'm able to successively build up state in the right order, which should match up with his expectations (and the documentation).

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]
LGTM

**Comment by deer** [comment]
Hey @marvinhagemeister, I updated the test to include the new route from the fixture. I suppose this isn't strictly necessary, but when I originally created the test I thought "I want to assert all the middleware routes". Since that thought happened, another middleware was added, so I threw it in.

Additionally I thought I'd share the inner workings of the sorting algorithm, since I somehow forgot that from before.

Before:
```
/layeredMdw{/*}? {/*}? 0
/layeredMdw/layer2{/*}? /layeredMdw{/*}? 0
/layeredMdw/layer2/layer3{/*}? /layeredMdw/layer2{/*}? 0
/layeredMdw/nesting/:tenant/:environment{/*}? /layeredMdw/layer2/layer3{/*}? 0
/layeredMdw/nesting/:tenant{/*}? /layeredMdw/nesting/:tenant/:environment{/*}? 0
/layeredMdw/nesting{/*}? /layeredMdw/nesting/:tenant{/*}? 0
/state-in-props{/*}? /layeredMdw/nesting{/*}? 0
```

After
```
/layeredMdw{/*}? {/*}? 1
/layeredMdw/layer2{/*}? /layeredMdw{/*}? 1
/layeredMdw/layer2/layer3{/*}? /layeredMdw/layer2{/*}? 1
/layeredMdw/nesting/:tenant/:environment{/*}? /layeredMdw/layer2/layer3{/*}? 1
/layeredMdw/nesting/:tenant{/*}? /layeredMdw/nesting/:tenant/:environment{/*}? -1
/layeredMdw/nesting/:tenant{/*}? /layeredMdw/layer2{/*}? 1
/layeredMdw/nesting/:tenant{/*}? /layeredMdw/nesting/:tenant/:environment{/*}? -1
/layeredMdw/nesting/:tenant{/*}? /layeredMdw/layer2/layer3{/*}? 1
/layeredMdw/nesting{/*}? /layeredMdw/layer2/layer3{/*}? -1
/layeredMdw/nesting{/*}? /layeredMdw{/*}? 1
/layeredMdw/nesting{/*}? /layeredMdw/layer2{/*}? 0
/state-in-props{/*}? /layeredMdw/nesting{/*}? -1
/state-in-props{/*}? /layeredMdw{/*}? 0
/state-in-props{/*}? /layeredMdw/layer2{/*}? -1
```

Finally, there were a few things with new names I had to uptake. handlers->multihandler and router->handler

**Comment by deer** [comment]
```
fresh-init subdirectory ... start up the server => ./tests/cli_test.ts:313:13
error: Leaking async ops:
  - 1 async operation to op_read was started in this test, but never completed.
  - 1 async operation to op_spawn_wait was started in this test, but never completed.
To get more details where ops were leaked, run again with --trace-ops flag.
```
This isn't from my test, but I'll still look into this since it's been causing some noise recently.

**Comment by deer** [comment]
Is there anything left to do here, @marvinhagemeister? I did follow up on the flakiness that caused the tests to fail: I ran them 500 times locally and couldn't reproduce the issue, so I'm not sure what else I can do for now.

**Comment by deer** [comment]
Well, this conflicts with your latest changes now. And it will conflict with my middle params PR, so I'll wait for that to get merged before fixing this.

**Comment by marvinhagemeister** [comment]
Nah I think it's good to be merged. Was just busy with other stuff. Merged the middle params PR.

**Comment by deer** [comment]
Ok, updated the ever-conflicting `fresh.gen.ts` and `main_test.ts` so this is finally good to go 🙌

**Pull request merged**
