### PR TITLE
docs: Add fresh_marionette to the Integrations section of the docs

### PR DESCRIPTION
**Pull request by digitaldesigndj**
I made a fresh module to help people get started with browser testing.

### CODE REVIEW

**Comment by hashrock** [comment]
I think just removing lock file will solve the problem :)

**Comment by digitaldesigndj** [comment]
You were right, thanks! Wish I saw this sooner

**Comment by digitaldesigndj** [comment]
Do these get squashed somewhere? The branch got kinda messy. Or related: do we mind?

**Comment by hashrock** [comment]
We can squash when we merge PRs so no worries. Please wait for review

**Review by severindupouy — APPROVED** [review]

**Review by kt3k — APPROVED** [review]
LGTM

**Review by iuioiua — APPROVED** [review]
LGTM. Thanks, @digitaldesigndj!

**Pull request merged**
