### PR TITLE
Disable VSCode experimental project setting

### PR DESCRIPTION
**Pull request by marcelocra**
Currently we get issues when running Deno in VSCode with the following setting enabled:

```json
"typescript.tsserver.experimental.enableProjectDiagnostics": true
```

Details in denoland/vscode_deno#595.

This PR disables that setting in the workspace generated file, so that beginners won't stumble on this.

ps: Deno is amazing! Thank you, folks!

### CODE REVIEW

**Comment by ahuigo** [comment]
@marcelocra  It seems that some typescript plug-in configuration conflicts with DENO plug-in configuration.

If so, it's not reasonable for Fresh to add this configuration.

**Comment by marcelocra** [comment]
> @marcelocra It seems that some typescript plug-in configuration conflicts with DENO plug-in configuration.
> 
> If so, it's not reasonable for Fresh to add this configuration.

It seems reasonable if this is preventing Fresh users (particularly new ones) from enjoying a good dev experience. You already set a bunch of Deno default settings.

Of course this is up to you to accept. But it cost me a couple of hours to figure out.

**Comment by ahuigo** [comment]
I agree that **good dev experience** is very important. Please wait for fresh's author to deal with your PR.

**Comment by iuioiua** [comment]
I'm unable to reproduce this issue. Do you still have this issue, @marcelocra?

**Comment by marvinhagemeister** [comment]
Closing, because the issue was in typescript and it has been resolved on their side.

**Comment by marcelocra** [comment]
Interestingly enough, I still need the `  "typescript.tsserver.experimental.enableProjectDiagnostics": false,` for the squiglies to disappear. Am I missing something at this point?

**Pull request closed without merging**
