### PR TITLE
docs: add "Contributing" section

### PR DESCRIPTION
**Pull request by iuioiua**
This just copies the main repo, which does the job.

### CODE REVIEW

**Comment by lucacasonato** [comment]
Can you add a section to the manual about "Contributing to `fresh`" with instructions on tests, fmt, and lint?

**Comment by deer** [comment]
I was thinking of working on https://github.com/denoland/fresh/issues/657, but then I saw this. Please close the issue once this is merged. I'd also suggest the link in `README.md` be changed to https://deno.com/manual/references/contributing#submitting-a-pr-to-fresh, so that people are taken to exactly the right place.

There's also the two closed https://github.com/denoland/fresh/pull/465 and https://github.com/denoland/fresh/pull/658. Before I delete my branch that introduces a `CONTRIBUTING.md` file (because what you have here seems like the preferred approach, I'd still recommend some sort of tips section. I had...
```
- [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary)
  are great when titling your PR.
- Tests, documentation, and examples always help to provide extra context.
- You'll likely need to install
  [deno-puppeteer](https://github.com/lucacasonato/deno-puppeteer#installation)
  in order to run the tests.
```

**Comment by iuioiua** [comment]
> I was thinking of working on #657, but then I saw this. Please close the issue once this is merged. I'd also suggest the link in `README.md` be changed to https://deno.com/manual/references/contributing#submitting-a-pr-to-fresh, so that people are taken to exactly the right place.

Done and done.

> - [Conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/#summary) are great when titling your PR.

Good idea. But this repo isn't the place to do that. I instead created an issue with this suggestion in the manual repo ([here](https://github.com/denoland/manual/issues/679)).

> - Tests, documentation, and examples always help to provide extra context.

Maybe let's get this PR landed first. We can explore how we can improve instructions in an issue or PR after.

> - You'll likely need to install [deno-puppeteer](https://github.com/lucacasonato/deno-puppeteer#installation) in order to run the tests.

~~I believe this is done anyway upon running `deno task test`~~

Ok, I'll add that in.

**Comment by iuioiua** [comment]
This PR is ready for review.

**Comment by deer** [comment]
https://github.com/denoland/manual/blob/main/references/contributing.md?plain=1#L165
What is the ` - this` doing at the end here? 🧐

**Comment by iuioiua** [comment]
Doh! Will fix 🥲

**Comment by iuioiua** [comment]
@marvinhagemeister, PTAL. I'll fix the typo mentioned in https://github.com/denoland/fresh/pull/1233#issuecomment-1590486475 independently.

**Comment by deer** [comment]
@marvinhagemeister Looks like this was inadvertently closed when manual#681 was merged.

**Comment by iuioiua** [comment]
Ready for review and merge, @marvinhagemeister.

**Review by marvinhagemeister — APPROVED** [review]

**Pull request merged**
