### PR TITLE
feat: support nested islands (#168)

### PR DESCRIPTION
**Pull request by michalvavra**
Collects children of the island (#168) and top level island when nested (#178).

I've added back tests removed in c8afee9.

### CODE REVIEW

**Comment by blakechambers** [comment]
Nice change.  I was looking into this over the weekend and got partway through a fix for this – but I took a bit of a different path that I thought worth mentioning.  

In my change, I used a context object to track whether the code is in an island or not.  You can see it here: 

https://github.com/denoland/fresh/compare/main...blakechambers:fresh:support-nested-islands#diff-b8e94e8d0640e34d87e2781f4a56590cec48f7704c8d8b72f532b7b750fc2da5R317-R335

This probably comes with a different set of pros and cons, but one thing a context allows is exposing a hook to detect whether you are in an island or not.  If that's something that feels useful, that could be another option.

**Review by lucacasonato — COMMENTED** [review]
I don't think this does what you think it does. The inner island is going to get hydrated by preact first, at which point it will start controlling the DOM elements.

Then the parent island gets hydrated by preact, which means it will take control over the entire DOM tree underneath the parent island (including the inner island). This means that the inner and outer island are now fighting over who gets to render the inner DOM nodes.

That obviously isn't ideal :)

**Comment by lucacasonato** [comment]
I think @blakechambers's approach is probably more reliable, because we can decide on the server to not hydrate an inner island at all. (I can't confirm this, because the git diff link you shared is not working).

**Comment by blakechambers** [comment]
@lucacasonato I'll clean up my branch and share here soon 👍

**Comment by blakechambers** [comment]
@lucacasonato I've updated my branch and submitted it as PR https://github.com/denoland/fresh/pull/517.

**Pull request closed without merging**
