### PR TITLE
chore: create manifest generation task

### PR DESCRIPTION
**Pull request by deer**
Hey @marvinhagemeister, your change in #2082 broke the functionality introduced in #1986. You can see the type checking failures here, now that I've generated the new manifests for all the fixtures.

In particular the manifest now looks like:
```ts
"./islands/MultipleCounters.tsx": $MultipleCounters,
```

but it really needs to be the original
```ts
"./islands/MultipleCounters.tsx": {
      CounterOne: $$MultipleCounters.CounterOne,
      CounterTwo: $$MultipleCounters.CounterTwo,
      default: $$MultipleCounters.default,
    },
```
or something similar. I thought relying on type checking would be enough to prevent regressions, but that's obviously not true. The gap to be filled is that we should always regenerate all manifest files when changing `manifest.ts`. (Your change snuck through because you didn't regenerate `fixture/fresh.gen.ts`.)

I'll open this as a draft for now, since it's late. Feel free to collaborate if you're feeling eager, otherwise I hope to get to this again tomorrow. (Right before basePath!)

### CODE REVIEW

**Comment by deer** [comment]
e.g.
```
error: TS2322 [ERROR]: Type 'typeof import("file:///Users/runner/work/fresh/fresh/tests/fixture/islands/MultipleCounters.tsx")' is not assignable to type 'IslandModule'.
  Property 'thisShouldNotCauseProblems' is incompatible with index signature.
    Type 'number' is not assignable to type 'ComponentType<any>'.
    "./islands/MultipleCounters.tsx": $MultipleCounters,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/runner/work/fresh/fresh/tests/fixture/fresh.gen.ts:202:5
```

**Comment by deer** [comment]
The other thing to do here is to finish my script so it's less hacky, and to add a new task to `deno.json`. Bonus points if the script runs as part of the `ok` task, but only if `manifest.ts` has changed. (Or something like that. I'll think about it more tomorrow.)

**Comment by deer** [comment]
The init tests now fail with the `--no-config` option, since we can't import the files anymore. I haven't looked to closely at how to work around this, but it seems like we might be able to split it up into two parts:
1. create `deno.json` with `--no-config`
2. do everything else using this newly created file

**Comment by marvinhagemeister** [comment]
+1 On adding a script to update all manifest files of test fixtures.

Regarding the manifest itself: The crux of the problem is that we must not import any "user" code during manifest generation because that can import files which contain mappings from the user's import map. Doing so breaks the init script when you run `deno run -A https://fresh.deno.dev` to bootstrap an application. It breaks even for imports referencing just `"preact"`. The `importLine` code imports the actual island/route files to check if exports are a function and that breaks the init script.

For the typing issue we should just loosen the manifest file type. It's a file completely generated by us and not modified by the user in any way. It's an internal implementation detail and we want to get rid of it anyways in the long term.

**Comment by deer** [comment]
When I run `deno run -A ../fresh/init.ts new_manifest` I don't have any issues. What's the issue?

I'll look into an alternate approach that avoids importing anything, just to see if it's feasible.

**Comment by marvinhagemeister** [comment]
It broke when I pointed it to the raw github URL like
 ```sh
 deno run -A https://raw.githubusercontent.com/denoland/fresh/9450d9d62b5abf67a4c029e468363f563d3978fe/init.ts
 ```
 
 It seems to work now though which makes me less sure of my initial assessment. Maybe I interpreted the symptoms wrong and it was caused by something else :S The tests with the `--no-config` flag reproduce that exact scenario. For as long as the CI is green we should be good.

**Comment by deer** [comment]
When I do:
```
deno run -Ar https://raw.githubusercontent.com/denoland/fresh/8418c639f4962a3473c26af5d8038ba3e9d309e9/init.ts
```
I don't have any problems. This is the import version (the first commit in this PR).

And then
```
deno run -Ar https://raw.githubusercontent.com/denoland/fresh/9450d9d62b5abf67a4c029e468363f563d3978fe/init.ts
```
also seems to be fine. This is the ts-morph version.

**Comment by deer** [comment]
One of the failures is #2062 again. Another is the following:
```
Error: R] No matching export in "tests/fixture_dev_legacy/main.ts" for import "default"

    data:application/javascript,import hydrate from "file:///D:/a/fresh/fresh/plugins/twind/main.ts";import options from "file:///D:/a/fresh/fresh/tests/fixture_dev_legacy/main.ts";export default function(state) { hydrate(options, state); }:1:76:
      1 │ ...lugins/twind/main.ts";import options from "file:///D:/a/fresh/fr...
        ╵                                 ~~~~~~~

An error occurred during route handling or page rendering.
Error: Build failed with 1 error:
data:application/javascript,import hydrate from "file:///D:/a/fresh/fresh/plugins/twind/main.ts";import options from "file:///D:/a/fresh/fresh/tests/fixture_dev_legacy/main.ts";export default function(state) { hydrate(options, state); }:1:76: ERROR: No matching export in "tests/fixture_dev_legacy/main.ts" for import "default"
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:[162](https://github.com/denoland/fresh/actions/runs/7044513115/job/19172340519?pr=2088#step:10:163)6:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:[178](https://github.com/denoland/fresh/actions/runs/7044513115/job/19172340519?pr=2088#step:10:179):11) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```

And [additionally](https://github.com/denoland/fresh/actions/runs/7044513115/job/19172340519?pr=2088):
```
allow opting out of client navigation => ./tests/partials_test.ts:764:6
error: TimeoutError: waiting for function failed: timeout 2000ms exceeded
      const timeoutError = new TimeoutError(
                           ^
    at new WaitTask (https://deno.land/x/puppeteer@16.2.0/vendor/puppeteer-core/puppeteer/common/IsolatedWorld.js:796:28)
    at IsolatedWorld.waitForFunction (https://deno.land/x/puppeteer@16.2.0/vendor/puppeteer-core/puppeteer/common/IsolatedWorld.js:662:22)
    at Frame.waitForFunction (https://deno.land/x/puppeteer@16.2.0/vendor/puppeteer-core/puppeteer/common/Frame.js:530:36)
    at Page.waitForFunction (https://deno.land/x/puppeteer@16.2.0/vendor/puppeteer-core/puppeteer/common/Page.js:2975:29)
    at waitForText (file:///D:/a/fresh/fresh/tests/test_utils.ts:410:16)
    at eventLoopTick (ext:core/01_core.js:178:11)
    at async file:///D:/a/fresh/fresh/tests/partials_test.ts:796:7
    at async withPageName (file:///D:/a/fresh/fresh/tests/test_utils.ts:232:7)
    at async file:///D:/a/fresh/fresh/tests/partials_test.ts:765:3

 FAILURES 

allow opting out of client navigation => ./tests/partials_test.ts:764:6
```
I'll see if I can reproduce this.

**Comment by marvinhagemeister** [comment]
Fix for the twind test https://github.com/denoland/fresh/pull/2100 . The way we bundle the twind options into the client bundle is super hacky.

**Comment by marvinhagemeister** [comment]
I found the root cause of the island mismatched type in https://github.com/denoland/fresh/pull/2101 . Basically we'd assume that we could type any export of an island module which is incorrect. In general we don't care what an island file exports. During startup we'll import that file anyway, loop through the exports and check which one of them is a function and treat that as a potential island. We'll know for sure if the function is an island or not when we're rendering it.

To me that strikes the proper balance between making assumptions about the user code and keeping our internals simple.

**Comment by deer** [comment]
Should I redo this to just provide the "generate all the manifests" functionality?

**Comment by marvinhagemeister** [comment]
A command to regenerate all manifests would be amazing 👍

**Review by marvinhagemeister — APPROVED** [review]
sweet 👍

**Pull request merged**
