### PR TITLE
feat: experimental support for `Deno.serve`

### LINKED ISSUE #678: Support the new `Deno.serve` API
The [new Deno.serve() API is supposed to offer significant performance improvements](https://deno.com/blog/v1.25#new-experimental-http-server-api) over the `http_server` used by Fresh.

Is Fresh open to supporting this new API (perhaps behind a flag to start?) Is this limited by Deno Deploy support?

Happy to do a PR if this would be interested. Let me know if you have prefs on the approach.

### PR DESCRIPTION
**Pull request by MarkBennett**
## Changes
Enables using the unstable `Deno.serve` API.

You can test the new server by:

1. setting the `opts` flag `experimentalDenoServe:true` in `/www/main.ts`
2. running, `deno run --unstable -A www/main.ts`

```ts
// /www/main.ts
// Start with unstable Deno.serve
await start(manifest, {
  plugins: [twindPlugin(twindConfig)],
  experimentalDenoServe: true,
});

```

Given the issues with requiring the `unstable` flag which the project seems to have avoided, it probably makes sense to hold off on merging until `Deno.serve` is stable and then switching over completely.

## TODO
* [ ] update tests
* [ ] add docs
* [ ] handle the `unstable` flag in tests, checks and tasks.

Closes #678

### CODE REVIEW

**Comment by MarkBennett** [comment]
This is not a complete PR as there are outstanding issues, but I've confirmed that the new server works by setting `experimentalDenoServe` to `true` in `www/main.ts`then running:

```
deno run --unstable -A www/main.ts
```

I'll keep iterating but feedback welcome @lucacasonato.

**Comment by lucacasonato** [comment]
@MarkBennett Looks good! I have pushed a change to add a `// @ts-ignore` comment to the `Deno.serve` invocation. This should alleviate the need to use `--unstable` across all tests (only for a single integration test that actually spawns a new `Deno.serve` server).

**Comment by MarkBennett** [comment]
> @MarkBennett Looks good! I have pushed a change to add a `// @ts-ignore` comment to the `Deno.serve` invocation. This should alleviate the need to use `--unstable` across all tests (only for a single integration test that actually spawns a new `Deno.serve` server).

Very cool. I didn't realize that you could use a `// @ts-ignore` directive like that.

Let me know what I can do to get this across the finish line. Do you want me to add an integration test for example? I've not done that before, but if you point me in the right direction I can connect the dots and update this PR.

**Comment by MarkBennett** [comment]
> @MarkBennett Looks good! I have pushed a change to add a `// @ts-ignore` comment to the `Deno.serve` invocation. This should alleviate the need to use `--unstable` across all tests (only for a single integration test that actually spawns a new `Deno.serve` server).

Thanks @lucacasonato Let me know what I can do to get this across the finish line. Do you want me to add an integration test for example? I've not done that before, but if you point me in the right direction I can connect the dots and update this PR.

**Comment by lucacasonato** [comment]
Yeah, integration test would be great. To do this:

1. Create a tests/fixture_experimental_serve containing a hello world project using this option
2. Add a test based off "jsx pragma works" in main_test.ts that starts this server, makes some requests to it, checks the requests are correct, and then stops the server.

If you get stuck anywhere, just LMK! :)

**Comment by lucacasonato** [comment]
I have added a test as I want to include this in the Fresh 1.1.0 release tomorrow.

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks!

**Comment by MarkBennett** [comment]
> LGTM, thanks!

Awesome. Excited for the next release! 🙂

**Pull request merged**
