### PR TITLE
feat: Expose routes #1649

### PR DESCRIPTION
**Pull request by RoeHH**
I saw this issue (https://github.com/denoland/fresh/issues/1649) here and thought, 'Hmm, why not just give it a go?' I am not sure if my approach to it was good, but I kinda like the idea.

### CODE REVIEW

**Comment by RoeHH** [comment]
While playing around with this i saw that it would be possible too add all Middlewares that apply to this Route or all handlers that exist in the fresh project

**Comment by RoeHH** [comment]
@marvinhagemeister review :) ?

**Comment by deer** [comment]
Hey @RoeHH, can you please merge main and deal with the conflicts? A lot has changed in `context.ts` since you created this a few weeks ago. It's probably best to make sure the PR is ready to go before trying to convince Marvin to take a look.

Two logistical points: 
* what about some documentation? As a user, how would I even discover this exists?
* I could also imagine the test being a bit more "functional" in the sense that your handler could create a "site map" or something similar. Then you could verify that your favorite route (perhaps your new "info-ctx" route) is included in the map. Of course the only way such a test could pass is if your code is working correctly.

For the actual code: 
* could you please clarify the name `FreshInfo`? I'm not sure we need a new type here, unless you have some ideas on other stuff that belongs inside this "info". It seems like you could just add `routes: Route<any>[]` to the context types and be done with it. 
* what about `UnknownHandlerContext` and `ErrorHandlerContext`? Right now they're feeling a bit left out. I guess there should at least be an explanation for why we don't want to pass the routes to these.

**Review by deer — CHANGES_REQUESTED** [review]
Hey @RoeHH, can you please merge main and deal with the conflicts? A lot has changed in `context.ts` since you created this a few weeks ago. It's probably best to make sure the PR is ready to go before trying to convince Marvin to take a look.

Two logistical points: 
* what about some documentation? As a user, how would I even discover this exists?
* I could also imagine the test being a bit more "functional" in the sense that your handler could create a "site map" or something similar. Then you could verify that your favorite route (perhaps your new "info-ctx" route) is included in the map. Of course the only way such a test could pass is if your code is working correctly.

For the actual code: 
* could you please clarify the name `FreshInfo`? I'm not sure we need a new type here, unless you have some ideas on other stuff that belongs inside this "info". It seems like you could just add `routes: Route<any>[]` to the context types and be done with it. 
* what about `UnknownHandlerContext` and `ErrorHandlerContext`? Right now they're feeling a bit left out. I guess there should at least be an explanation for why we don't want to pass the routes to these.

**Pull request closed without merging**
