### PR TITLE
Add documentation section in readme and fix blue links

### PR DESCRIPTION
**Pull request by sylc**
1. The online documentation link is not easy to find. It is currently only showing in the about section which is hidden quickly when scrolling down to read the readme. I have added a more explicit section in the readme.

2. In the online home page the blue color is not showing up as it is used not present in the theme.
    before 
    image
    after 
    image

### CODE REVIEW

**Comment by thegaryroberts** [comment]
The main Readme could do with a clearer link to the wonderful published site. It has a link at the bottom that confusingly points at the doc files in the repo instead. Can this be fixed as part of this too?

I usually find the published site via my browser history as I have no idea how I found it in the first place.

**Comment by sylc** [comment]
> The main Readme could do with a clearer link to the wonderful published site. It has a link at the bottom that confusingly points at the doc files in the repo instead. Can this be fixed as part of this too?

@thegaryroberts  This is already part of the PR.

**Comment by thegaryroberts** [comment]
Sorry I misunderstood your description and just thought you were changing the colour, didn't know you had changed the link ref too. I should've looked at the code diff. Thanks!

**Review by lucacasonato — APPROVED** [review]
Thanks

**Pull request merged**
