### PR TITLE
fix: Add `_fresh` to .gitignore on update

### LINKED ISSUE #1680: Add `_fresh` to gitignore on update
Seems like we don't add that on update.

### PR DESCRIPTION
**Pull request by smitssjors**
Fixes #1680

### CODE REVIEW

**Review by marvinhagemeister — COMMENTED** [review]
Awesome, this is great! Let's add a quick test to the existing update test that verifies that this works 👍

**Comment by smitssjors** [comment]
I added some test but there are some things I would like to add.

- I found it difficult to find the tests
- There is some room for refactoring the update tests

I don't mind picking up some of this work. I would suggest splitting the tests into `init_test.ts` and `update_test.ts`.

Also, why import the asserts from `deps.ts` and not directly from `$std`?

**Comment by marvinhagemeister** [comment]
> I don't mind picking up some of this work. I would suggest splitting the tests into `init_test.ts` and `update_test.ts`.

Agree, splitting these up makes sense.

> Also, why import the asserts from `deps.ts` and not directly from $std?

That was before my time, but I'd guess that this was done so that there are less places to update when moving to a newer version of std.

**Review by marvinhagemeister — APPROVED** [review]
This is great! Thank you so much for fixing this 👍

**Pull request merged**
