### PR TITLE
feat: added support for static folder in FreshOptions

### LINKED ISSUE #460: Can support custom static folder?
My static in other directory because my front-end code is a separate project

### PR DESCRIPTION
**Pull request by frostzt**
### Description

Support custom (user provided) static assets folder or fallback to default behavior.
Closes: https://github.com/denoland/fresh/issues/460

---

### File Changes

- `src/server/context`: changed the file to now look for `staticDir` first
- `src/server/types`: added `staticDir` to the `FreshOptions` interface

### CODE REVIEW

**Review by lucacasonato — APPROVED** [review]
Thanks!

**Comment by lucacasonato** [comment]
Actually, can you add a test?

**Comment by frostzt** [comment]
Sure! Btw are there any written docs for `fresh` so that I can get an insight on writing tests?
I have written a test for thing that I have tried to do, I don't really think that's the right way though, would love to have your insights on this @lucacasonato !

**Review by lucacasonato — APPROVED** [review]
No docs right now. I should add some (and a CONTRIBUTING.md). The test looks good. Thanks!

**Pull request merged**
