### PR TITLE
feat: add component/Button in starter project

### PR DESCRIPTION
**Pull request by asrvd**
added a new Button component as requested in issue #350 , has been tested.

@lucacasonato shall I update the start command to watch the `components/` folder too ?

### CODE REVIEW

**Comment by asrvd** [comment]
updated example project dir name to `deno-fresh-demo` following #342

**Review by santosant — APPROVED** [review]

**Review by lucacasonato — COMMENTED** [review]
Thanks, but this is a kind of weird if a user chooses not to use `twind` (because then the wrapper does nothing). Maybe add the `disabled` stuff to the `Button` component too?

**Comment by asrvd** [comment]
> Thanks, but this is a kind of weird if a user chooses not to use `twind` (because then the wrapper does nothing). Maybe add the `disabled` stuff to the `Button` component too?

yes, will do 👍🏼

**Comment by asrvd** [comment]
@lucacasonato the `disabled` thing is already being passed as a prop, the import was unnecessary, removed it.

**Review by lucacasonato — APPROVED** [review]
I made some tweaks, but LGTM now.

**Pull request merged**
