### PR TITLE
Update showcase.json

### PR DESCRIPTION
**Pull request by femo-dev**
Magic-Link-Login is a simple but powerful example that will show you how to build a web application with Deno Fresh that allows users to sign up and sign in with a magic link provided by Supabase, as well as update your profile data, including your profile photo.

### CODE REVIEW

**Comment by femo-dev** [comment]
Hello, I would like to publish my web app Magic Link Login in the Deno Fresh showcase but I don't know how to upload the images. I don't know if the command "deno task screenshot [url] [your-app-name]" has this purpose and if so I don't know how to use it until now. Anyway, I have attached these images. I stay tuned to your observations and any help that you can give me if necessary. Thanks so much.
magic-link-login1x
magic-link-login2x

**Comment by marvinhagemeister** [comment]
@FabianMendoza7 The command `deno task screenshot [url] [your-app-name]` needs to be run inside the fresh repository. If we'd like to add - let's say - https://example.com to the showcase it would be `deno task screenshot https://example.com example.com`

**Comment by femo-dev** [comment]
Hello Marvin.

I already ran the screenshot command. First I had to install another dependency (see image), please tell me what is the next step. Thanks.

Onscreenshot

**Comment by femo-dev** [comment]
Hello Marvin.

I already ran the screenshot command. First I had to install another dependency (see image), please tell me what is the next step. Thanks.

[Onscreenshot]

Fabián.
________________________________

**Comment by femo-dev** [comment]
> Hello Marvin.
> 
> I already ran the screenshot command. First I had to install another dependency (see image), please tell me what is the next step. Thanks.
> 
> Onscreenshot

Additionally, in the json I had put my app data in this way:

  {
    "title": "Magic Link Login",
    "link": "https://magic-link-login.deno.dev/",
    "github": "FabianMendoza7/magic-link-login",
    "image": "magic-link-login"
  },
  
Would we need to correct something? I ask you because in the "image" property I put "magic-link.login" but in the command screenshot, I put "magic-link-login.deno.dev", as you told me. Or has nothing to do?

Also, I can't do push (I don't have permissions).

Thanks for you reply.

**Comment by femo-dev** [comment]
Hello, I've already run the screenshoot command. Thanks.

**Comment by femo-dev** [comment]
I just reopened this pull request, I had closed it by error.

**Comment by marvinhagemeister** [comment]
Closing, as the PR is incomplete and there hasn't been interested in bringing this over the finish line.

**Pull request closed without merging**
