### PR TITLE
added linksapp fresh demo

### PR DESCRIPTION
**Pull request by harshmangalam**
linksapp-fresh demo web app

### CODE REVIEW

**Comment by hashrock** [comment]
Nice app! could you add screenshots?

https://github.com/denoland/fresh#adding-your-project-to-the-showcase

**Comment by harshmangalam** [comment]
I got this error while running screenshot command
```deno task screenshot https://linksapp.deno.dev/ linksapp```

```
error: Uncaught Error: Could not find browser revision 1022525. Run "PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts" to download a supported browser binary.
      if (missingText) throw new Error(missingText);
                             ^
    at ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:99:30)
```

**Comment by hashrock** [comment]
hmm could you try the command in the error log?
> PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts

**Comment by harshmangalam** [comment]
deno_puppetter cmd worked successfully but again i tried screenshot cmd i got new err
```error: Uncaught Interrupted: operation canceled
    const result = await reader.read(inspectArr);
                   ^
    at async read (deno:runtime/js/12_io.js:105:19)
    at async readDelim (https://deno.land/std@0.93.0/io/bufio.ts:652:20)
    at async readStringDelim (https://deno.land/std@0.93.0/io/bufio.ts:702:20)
    at async readLines (https://deno.land/std@0.93.0/io/bufio.ts:711:18)
    at async waitForWSEndpoint (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:168:20)
    at async BrowserRunner.setupConnection (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:146:31)
    at async ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:114:26)
```

**Comment by ajvanegasv** [comment]
> I got this error while running screenshot command `deno task screenshot https://linksapp.deno.dev/ linksapp`
> 
> ```
> error: Uncaught Error: Could not find browser revision 1022525. Run "PUPPETEER_PRODUCT=chrome deno run -A --unstable https://deno.land/x/puppeteer@16.2.0/install.ts" to download a supported browser binary.
>       if (missingText) throw new Error(missingText);
>                              ^
>     at ChromeLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:99:30)
> ```

I am getting the same error. How do I solve this problem so that I can share my portfolio?

**Pull request merged**
