### PR TITLE
docs: add src directory guide to create-a-project

### PR DESCRIPTION
**Pull request by greym0uth**
Creates documentation for #257 

This adds a guide on using the `src`, or any other, directory for code, routes, islands, etc. instead of at the root of the project.

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
I don't think this is something we should add to the "Getting Started". A page in concepts would be better I think.

The "Getting Started" guide should have as few decision points for devs as possible.

**Comment by alirani** [comment]
Hello I tried following the steps you documented, but fresh.gen.ts generate `import config from "./deno.json" assert { type: "json" };` which is an error since deno.json is at the root and not in /src directory

**Comment by solofeed** [comment]
Same problem as for @alirani

**Comment by iuioiua** [comment]
Sorry for the delay, @greym0uth. Could you please update and test the doc? Note: imports now live within `deno.json` for new projects instead of `import_map.json`.

**Comment by iuioiua** [comment]
I am closing this in favour of #1286.

**Pull request closed without merging**
