### PR TITLE
Docs fix typo

### PR DESCRIPTION
**Pull request by antoninbeaufort**
Fix some typos in docs, "middlware" becoming "middleware", an "peform" becoming "perform".

### CODE REVIEW

**Comment by hashrock** [comment]
I'm trying to fix this CI error(should be not related in this PR)

https://github.com/lucacasonato/fresh/runs/6586752640?check_suite_focus=true#step:6:22

When I run ci on macOS and ubuntu at the same time, esm.sh appears to return a 403 forbidden error.

**Comment by lucacasonato** [comment]
cc @ije: have you seen this esm.sh issue before?

**Comment by ije** [comment]
Screen Shot 2022-05-27 at 09 30 59

seems it was blocked by Cloudflare Security

**Comment by ije** [comment]
but i never add any Firewall filters in fact, i don't know why

**Review by hashrock — COMMENTED** [review]
I think your changes are right, but I got an error here:

> resp.headers.set("X-Custom-Header", "Hello");

`resp` type is `Response | Promise<Response>` , maybe we should use `await` at `ctx.render()`?

**Review by lucacasonato — APPROVED** [review]
LGTM, thank you @AntoninBeaufort.

@hashrock I addressed the missing `await` now.

@ije Thanks for looking into the esm.sh issue :)

**Pull request merged**
