### PR TITLE
Rename my-app to my-project in landing page

### PR DESCRIPTION
**Pull request by xyntechx**

### CODE REVIEW

**Comment by nikableh** [comment]
While I agree that what fresh is — is more of a _"project"_ than an _"app"_, I think that it's not too important what this suggested name is. And at the same time, changing such things may potentially cause confusion or break something.

**Review by lucacasonato — APPROVED** [review]
Thanks, the docs are written using `my-project`, so lets use that uniformly.

**Comment by xyntechx** [comment]
Awesome! Thanks for the merge :) @synalice apologies for not specifying why I made the change!

**Comment by nikableh** [comment]
> Awesome! Thanks for the merge :) @synalice apologies for not specifying why I made the change!

Oh, I didn't realize the documentation was using `my-project` :sweat_smile:

**Pull request merged**
