### PR TITLE
fix(server): don't crash if no islands folder is present

### PR DESCRIPTION
**Pull request by marvinhagemeister**
I feel like the island folder should be optional and not lead to an error when it's missing.

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
Need to take another look. The test is passing although it shouldn't.

**Comment by iuioiua** [comment]
I wasn't able to reproduce this issue with the latest init script. What was the error that you were getting?

**Comment by marvinhagemeister** [comment]
This is the error I was getting:

Screenshot 2023-06-08 at 01 19 38

**Comment by iuioiua** [comment]
Ok, I can reproduce the issue. I previously used the init script from the website, which must've been cached. My bad.

**Comment by deer** [comment]
For anyone curious: this was solved by https://github.com/denoland/fresh/pull/1327.

**Pull request closed without merging**
