### PR TITLE
refactor: changed Handlers type to MultiHandler

### PR DESCRIPTION
**Pull request by aushwin**
This PR is for issue #1350 

Hey @marvinhagemeister, I did not get what you meant in the 4th step. Kindly help me out here 
https://github.com/denoland/fresh/issues/1350#issuecomment-1605394508

### CODE REVIEW

**Comment by choucavalier** [comment]
@aushwin i think what @marvinhagemeister meant was to check that the user exported a function called `handlers` (with an "s") instead of `handler` (without an "s"). this would help detect confused users who try to create a `handler` but naming the function incorrectly might lead them to think their `handler` is not working, bang their head against their desk for 3 days, and then plunge into depression as they realise they had an extra "s" in their function name. but maybe i misunderstood

**Review by marvinhagemeister — COMMENTED** [review]
@aushwin  This looks great!! Let's run a quick `deno fmt` and `deno lint` to ensure the changes match the expected formatting. After that it's ready to be merged 👍

**Comment by marvinhagemeister** [comment]
@tgy Yeah exactly. I think the type hints in the editor are good enough and gets us 80% there already. Like you said, I was referring to checking the actual exported values from the modules which might be neat. It's more for bonus points and can happen in another PR too.

**Comment by aushwin** [comment]
@marvinhagemeister @tgy  is it something like this 
`MODULE_EXPORT_HANDLERS` is a constant for the string `handlers`
image

And am getting this error in my terminal.
image

**Comment by aushwin** [comment]
But I guess we need to show this in the error container right ?

**Comment by aushwin** [comment]
Hi @marvinhagemeister Any updates on this ?

**Review by marvinhagemeister — APPROVED** [review]
LGTM, thanks for the PR 🎉

**Pull request merged**
