### PR TITLE
New Project: diKnow

### PR DESCRIPTION
**Pull request by xyntechx**
For the image, we can use a screenshot of the diKnow homepage. I'm not sure where to place the image in this repo though!

### CODE REVIEW

**Comment by dector** [comment]
Few nit-picks:
- Search is not reacting to "Enter" key press - I need to grab a mouse and click on the "search" button;
- Most of my search requests are fulfilled (I tried tirano, tiranosaur, tiranosaurio etc - "diplo" worked but that's the only successful one). Maybe that's a good idea to show few first/random dinos on first load;
- What do you think partial matching-on-typing?

**Comment by xyntechx** [comment]
- Noted on the `Enter` keypress. I'll make the improvement!
- I'm not sure what you mean by "diplo is the only successful one", but sure I'll work on the random list of dinos on mount.
- Partial matching is actually much easier than complete matching, but I feel that complete matching is important to have so that when you type one letter (e.g. "a"), hundreds of dinos won't show up 😂

**Comment by xyntechx** [comment]
Updates are done!

**Comment by hashrock** [comment]
@xyntechx 
Lovely site!

for screenshots, try this (merge main before executing): 
> deno task screenshot https://xyntechx-diknow.deno.dev/ diKnow

**Comment by xyntechx** [comment]
Okay screenshots are included now!

**Review by hashrock — APPROVED** [review]
LGTM!

**Pull request merged**
