### PR TITLE
fix: 128 routes/[id]/[path] catches request for _frsh/refresh.js

### LINKED ISSUE #128: `./routes/[id]/[path].tsx` catches request for `_frsh/refresh.js`
Should we move this block up?
https://github.com/lucacasonato/fresh/blob/026ed86f4009fc0a35463d43218bf8c34aead98e/src/server/context.ts#L395

### PR DESCRIPTION
**Pull request by kuboon**
Fixes #128
Requests with INTERNAL_PREFIX should be handled before all other routes.

### CODE REVIEW

**Review by lucacasonato — COMMENTED** [review]
Could you add a test for this to the `tests/` directory?

**Comment by kuboon** [comment]
I added this new route on `tests/fixture/fresh.gen.ts`
```
    "./routes/[...all].ts": $16,
```
and found that these 2 tests fails.
```
/books/:id page - /books/abc
/api/xyz not found
```
404 expected / 200 actual (because new route catches it)

Which is better?
1. change above 2 expectations to 200
2. prepare another fixture set
3. anything else

**Comment by lucacasonato** [comment]
Could you either do it in the other fixture (fixture_error), or add another fixture? If you'd rather I do this, just let me know 🙂

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
