### PR TITLE
Navigate Documentation with Unicode Arrows

### PR DESCRIPTION
**Pull request by WardCunningham**
Prefer unicode arrows to those made of ascii art.

I continue my Fresh tutorial by forking, editing, and testing the fresh www server.

Notice how nice the arrows at the bottom of this screen shot look. Sweet.

image

### CODE REVIEW

**Review by lucacasonato — APPROVED** [review]
Thanks!

**Comment by WardCunningham** [comment]
Automation seems stalled. Does this pull request need more approval?

**Comment by lucacasonato** [comment]
CI has not run yet. Just started it.

**Comment by WardCunningham** [comment]
Thanks for pushing this through.

I think I broke it when I changed the title to "Navigate Documentation with Unicode Arrows". That is when the "requested deployment preview" status changed to "abandoned".

**Pull request merged**
