### PR TITLE
Update documentation for 'Internal Server Error' page behavior

### LINKED ISSUE #1978: "_500.tsx" Not Rendering in Dev Mode
I had some trouble setting up a custom error page for my app. I found that the _500.tsx page only seems to show up when I run the app in preview mode. Is there a way I can make it appear in dev mode? In dev mode, the error message is quite descriptive, but I'm wondering if it's possible to show the custom _500.tsx page instead of the default dev error page.

I have a handler intentionally throwing an error:

```ts
export const handler: Handlers<Props> = {
  async GET(_req, ctx) {
    throw new Error('Some error inside the handler');
  }
};
```

When I run in dev mode using `deno run -A --watch=static/,routes/ dev.ts`, I see this screen:

image

When running in preview mode with `deno run -A main.ts`, this is the screen that appears (my _500.tsx component):

image

These are my dev.ts and main.ts files:

`dev.ts`
```ts
#!/usr/bin/env -S deno run -A --watch=static/,routes/

import dev from 'fresh/dev.ts';
import config from './fresh.config.ts';

import '$std/dotenv/load.ts';

await dev(import.meta.url, './main.ts', config);
```

`main.ts`
```ts
/// <reference no-default-lib='true' />
/// <reference lib='dom' />
/// <reference lib='dom.iterable' />
/// <reference lib='dom.asynciterable' />
/// <reference lib='deno.ns' />

import '$std/dotenv/load.ts';

import { start } from 'fresh/server.ts';
import manifest from './fresh.gen.ts';
import config from './fresh.config.ts';

await start(manifest, config);
```

Fresh version: 1.5.2
Deno version: 1.37.2

Thanks in advance :)

### PR DESCRIPTION
**Pull request by gustavomaltez**
As described on #1978, the custom '500 Internal Server Error' page is not displayed when the app is running in dev mode. This can be confusing for developers, and it took me some time to realize this behavior.

This PR aims to address the issue by updating the documentation to clarify the default behavior of 'Internal Server Error' pages. It will help other developers understand how these pages work.

closes #1978

### CODE REVIEW

**Review by deer — APPROVED** [review]
Take a look at #1984 for an example of how you can get github to link the PR with the issue. See the github [docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more information.

As I mentioned in my PR, we have a soft conflict here since I'm branching this page to the canary docs. (Because the feature I'm adding isn't released yet.) Just a note to Marvin: don't merge both of these at the same time.

But as for the actual content: this looks like the right combination of words to describe what's going on. It's much more clear now. Thanks!

**Comment by gustavomaltez** [comment]
Thanks! I've just updated the PR description, mentioning that this PR will resolve issue #1978. How should we handle the conflicts? Can we merge your PR first, and then I'll update my branch with your changes and also make the necessary updates to the error-pages.md in the canary docs?"

**Comment by deer** [comment]
I suppose it doesn't matter a whole lot. As long as they don't get merged at the same time, whoever goes second will have to respond to the first PR.

**Comment by gustavomaltez** [comment]
Since your PR has been merged, I've updated my branch with the latest changes from the main branch and added the new documentation for the custom 500 error page to the canary docs.

**Comment by deer** [comment]
Hi @gustavomaltez, it looks like there's a formatting issue. Please make sure to run `deno task ok` before submitting changes in order to reduce the amount of back and forth.

**Comment by gustavomaltez** [comment]
Sorry about that, I just pushed a commit with the fix. Please check if it's correct.

**Review by deer — APPROVED** [review]
Thanks Gustavo.

@marvinhagemeister, I think this one is ready.

**Comment by deer** [comment]
@marvinhagemeister, this one can be closed as well, due to #2074.

**Comment by marvinhagemeister** [comment]
Yup, the next version of Fresh shows errors in an Error overlay which can be closed.

**Pull request closed without merging**
