### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by nikableh**
It's not the best one, but might be a good place to start.

### CODE REVIEW

**Review by fdemir — APPROVED** [review]
nice

**Comment by un-versed** [comment]
Nice! I was missing this...

What about commit messages? Should we have a pattern?

Personally I like to use https://www.conventionalcommits.org/en/v1.0.0/

**Comment by nikableh** [comment]
@un-versed, absolutely agree. They are very nice and already seem to be the standard for the repository.

Although I'm not sure if it's necessary to add this into `CONTRIBUTING.md` since all PRs when merged get squashed into single properly named commit.

@lucacasonato, what do you think?

**Comment by iuioiua** [comment]
Closing this as Deno repos mainly refer to a central [Contributing page](https://deno.com/manual@v1.34.1/references/contributing). We're adding the link to that page in the README in #1233.

**Pull request closed without merging**
