### PR TITLE
feat: async renderer

### PR DESCRIPTION
**Pull request by so1ve**
If the render function can't be async, I can't use unocss :(

### CODE REVIEW

**Comment by so1ve** [comment]
BTW, using unocss instead of twind seems like a good idea.

**Review by lucacasonato — COMMENTED** [review]
Can you add a test for this? To do this you can just make the render function in `./tests/fixture/routes/_render.ts` async and add an `await new Promise((r) => r());` in the function body.

**Comment by so1ve** [comment]
ok, like this?

**Review by lucacasonato — APPROVED** [review]
LGTM, thanks!

**Comment by lucacasonato** [comment]
If you get unocss working, it'd be fantastic if you could add a page to the `docs/` folder about how users can use UnoCSS with fresh. I think people would really find that very useful :-)

**Pull request merged**
