### PR TITLE
feat: added my cursed little project to the showcases

### PR DESCRIPTION
**Pull request by NinekoTheCat**
I made a project to integrate the features I think were missing to deno using a monorepo please accept this cursed project into the showcases

https://github.com/NinekoTheCat/Fresh-Vite-Preact

### CODE REVIEW

**Comment by kt3k** [comment]
Could you add screenshots of the app by following the steps in README https://github.com/denoland/fresh#adding-your-project-to-the-showcase

**Comment by NinekoTheCat** [comment]
I don't know how I'd do that @kt3k  it's not a website just a template project that I managed to make, to make fresh devs' lives easier

**Comment by iuioiua** [comment]
Hi @NinekoTheCat, even a screenshot of a base app built with your tool would suffice. Once you've added a screenshot, we can add it in 👍🏾

**Comment by iuioiua** [comment]
Closing this PR as it's gone stale. Feel free to open a new PR if you're able to grab a screenshot 🙂

**Pull request closed without merging**
