### PR TITLE
Update showcase.json

### PR DESCRIPTION
**Pull request by vorcigernix**
Adding my personal website (source available)

### CODE REVIEW

**Comment by hashrock** [comment]
Cool site! could you add screenshots using `deno task screenshot`?

**Comment by vorcigernix** [comment]
I don't have this command in tasks, but I can create screenshot. What resolution?

**Comment by hashrock** [comment]
2x: 1200x675
1x: 600x338

see:
https://github.com/denoland/fresh/tree/main/www/static/showcase

**Comment by vorcigernix** [comment]
Added in https://github.com/denoland/fresh/pull/795

**Pull request closed without merging**
