### PR TITLE
chore: bump deps and update copyright year v2

### PR DESCRIPTION
**Pull request by lino-levan**
Let's try this again... because of @lucacasonato's work, this now works in deploy

### CODE REVIEW

**Comment by lino-levan** [comment]
@hashrock please take a look!

**Comment by hashrock** [comment]
I will be pair programming with kt3k next week, so we'll look then.

I'm not familiar with why this was revert last time, but wasn't it related to this issue? If so, it would be nice to have this test.

https://github.com/denoland/fresh/issues/1012

**Comment by lino-levan** [comment]
I will see if I can somehow add a test

**Review by kt3k — APPROVED** [review]
We tested this branch ( https://github.com/denoland/fresh/tree/test-pr-1069 ) and [the preview](https://fresh-s7wgg751sydg.deno.dev/) looked working. LGTM

**Review by hashrock — APPROVED** [review]

**Pull request merged**
